// importaciones
import type { Metadata } from "next"; // Proporciona tipado fuerte para los metadatos globales de Next.js.
import "./globals.css"; // Estilos globales que se aplican a toda la aplicación.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; // Define los metadatos básicos (título y descripción) visibles en navegadores y buscadores.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">{/* Elemento raíz HTML que fija el idioma del documento */}
      <body className="antialiased">
        {/* Aplica las fuentes registradas y un suavizado tipográfico para todo el body */}
        {children}
        {/* Inyecta la jerarquía de componentes de cada página dentro del layout global */}
      </body>
    </html>
  );
}
